### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '[' on line 17

### ISSUE THREAD

**Issue by kdekooter** [nabossha/ZEServices#2]
First of all: very nice job! This will allow us to build proper software for our car :-).

When I try to run the software I see the following error in my server log:

`PHP Parse error:  syntax error, unexpected '[' in /var/www/html/[..]/application.php on line 17`

Looking at the source file I do not see syntax errors. Would the PHP version make a difference?

**Comment by nabossha** [comment]
yes, the used syntax is PHP 5.4 and above, so if your PHP-version is less then 5.4 you may try to  to adjust line 17 to: 
`$vehicleData = array();`
