### ISSUE TITLE
Can't make it works

### ISSUE THREAD

**Issue by goRaspy** [nabossha/ZEServices#3]
Hello, I'm can't make Z.E.Garage works.
Could you furnish an example for "vehicles" and "Zeus" field in config file ?

Regards

**Comment by nabossha** [comment]
well, the provieded code is already a sample configuration. i am sorry but if you don't understand how to enter your credentials into the code you are likely not able to install the application on a server too...

**Comment by goRaspy** [comment]
Hi, thanks for your message. I do not think I have any problems with my server. I tried several config tests but unfortunately I just have the "Daten aktualisieren" button but it do not works properly (no effect on screen and in vehicules.json).

For me I just have to change login / password and VIN in config file.  But I have a doubt for "vehicles" and "Zeus" lines in config files. Should I change something else on this line ? If yes, what is the expected data ?

Tks if you can help me on this specific point.

**Comment by jellepals** [comment]
Hey GoRaspy,

I moved the config content to application.php. After that change, the code works for me. I think there was some problem with the "require" command.

**Comment by MartinRyx** [comment]
I had to make some changes to the code to make it work:

#### In application.php

I had to add some timezone settings. For me, in Sweden, it looks like this:
`date_default_timezone_set("Europe/Stockholm");`
I also changed `require 'config.php';` to `require __DIR__.'/config.php';`

#### In config.php

I had to provide a full path here too. I changed the row `"JSONfile"      => "vehicles.json",` to `"JSONfile"      => __DIR__."/vehicles.json",`

I also had to an end of the php-tag so it was a correct block of `<?php ... ?>`

After that it worked like a charm. Well, I plan to do some translations too, but for now I'm only using it to get the json and save all values in a database

**Comment by goRaspy** [comment]
Hi, many thanks for your help. Works fine with my Fluence ZE.
Finally I applied MartinRyx tweaks and moved the config content to application.php like suggested by jellepals. 

I also created a "MY VIN NUMBER".xml on server and furnish right to apache.

Many thanks it is awesome :)
