### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by macjl** [nabossha/ZEServices#5]
Hello,

I'm unable to obtain ZE infos with the php script. When I try to connect, curl response bring this error : 

```
HTTP/1.1 400 Bad Request
Set-Cookie: JSESSIONID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; Path=/aqPortal; Secure
Content-Type: text/xml, charset=UTF-8
Content-Length: 496
Date: Mon, 16 May 2016 12:19:55 GMT
Connection: close
Server: Renault EV

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:FailureResponse xmlns:ns4="urn:com:renault:smartphone.userservices:v1" xmlns:ns3="urn:com:renault:gdc:type:portalcommon:v1" xmlns:ns5="urn:com:hitachi:gdc:type:authenticationmanagercommon:v1" xmlns:ns2="urn:com:renault:gdc:type:user:v1">
    <ns3:ErrorCode>-2000</ns3:ErrorCode>
    <ns3:ErrorMessage>com.airbiquity.common.http.AqHttpException: java.net.ConnectException: Connection timed out</ns3:ErrorMessage>
</ns3:FailureResponse>
```

Is the php code still working?

**Comment by MartinRyx** [comment]
No, not in the current state. Renault changed the API with the new app. It now uses JSON instead of XML for the requests. Tonight I started to find out how the new API works and so far I have not find any difficulties :-)

**Comment by nabossha** [comment]
Hi folks - i have re-worked the whole application and it works now with the new Z.E. Services (JSON-API) from Renault. have fun!

**Comment by macjl** [comment]
Hello. It's working fine for me! Thank you for your work!
